using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Serialization;
using cdsi.refData;

namespace cdsi
{
    public static class RefData
    {
        public static double Version => 4.5;

        /// <remarks>
        /// As of .NET Core 3.1 the ScheduleSupportingData.cs file generated by xsd.exe has an incorrect property type.
        /// Edit the file to change scheduleSupportingDataObservationCodedValuesCodedValue[][] to scheduleSupportingDataObservationCodedValuesCodedValue[]
        /// TODO: find a better way to fix this. Partial classes?
        /// </remarks>
        public static scheduleSupportingData Schedule
        {
            get
            {
                var name = "cdsi.refData.xml.ScheduleSupportingData.xml";
                var assembly = Assembly.GetExecutingAssembly();
                var resource = assembly.GetManifestResourceStream(name);
                var deserializer = new XmlSerializer(typeof(scheduleSupportingData));
                return (scheduleSupportingData)deserializer.Deserialize(resource);
            }
        }

        public static IDictionary<string, antigenSupportingData> Antigen { get; } = new AntigenCollection();
    }

    public class AntigenCollection : IDictionary<string, antigenSupportingData>
    {
        public antigenSupportingData this[string key]
        {
            get
            {
                var name = $"cdsi.refData.xml.AntigenSupportingData- {key}-508.xml";
                var assembly = Assembly.GetExecutingAssembly();
                var resource = assembly.GetManifestResourceStream(name);
                var deserializer = new XmlSerializer(typeof(antigenSupportingData));
                return (antigenSupportingData)deserializer.Deserialize(resource);
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public ICollection<string> Keys
        {
            get
            {
                var re = new Regex("cdsi\\.refData\\.xml\\.AntigenSupportingData- (.*)-508\\.xml");
                var assembly = Assembly.GetExecutingAssembly();
                var resources = assembly.GetManifestResourceNames();
                return resources.Where(r => r.EndsWith(".xml")).Select(r => re.Match(r).Groups[1].Value).ToList();
            }
        }


        public ICollection<antigenSupportingData> Values => Keys.Select(k => this[k]).ToList();

        public int Count => Keys.Count;

        public bool IsReadOnly => true;

        public void Add(string key, antigenSupportingData value)
        {
            throw new NotImplementedException();
        }

        public void Add(KeyValuePair<string, antigenSupportingData> item)
        {
            throw new NotImplementedException();
        }

        public void Clear()
        {
            throw new NotImplementedException();
        }

        public bool Contains(KeyValuePair<string, antigenSupportingData> item)
        {
            return item.Key.Equals(this[item.Key]);
        }

        public bool ContainsKey(string key)
        {
            return Keys.Contains(key);
        }

        public void CopyTo(KeyValuePair<string, antigenSupportingData>[] array, int arrayIndex)
        {
            throw new NotImplementedException();
        }

        public override bool Equals(object obj)
        {
            return base.Equals(obj);
        }

        public IEnumerator<KeyValuePair<string, antigenSupportingData>> GetEnumerator()
        {
            return Keys.Select(k => new KeyValuePair<string, antigenSupportingData>(key: k, value: this[k])).GetEnumerator();
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public bool Remove(string key)
        {
            throw new NotImplementedException();
        }

        public bool Remove(KeyValuePair<string, antigenSupportingData> item)
        {
            throw new NotImplementedException();
        }

        public override string ToString()
        {
            return base.ToString();
        }

        public bool TryGetValue(string key, [MaybeNullWhen(false)] out antigenSupportingData value)
        {
            var success = true;
            try
            {
                value = this[key];
            }
            catch
            {
                value = null;
                success = false;
            }
            return success;
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
