using System.Collections.Generic;
using Cdsi.ReferenceData;
using Cdsi.SupportingData;

namespace Cdsi
{
    public static class Reference
    {
        /// <remarks>
        /// As of .NET Core 3.1 the ScheduleSupportingData.cs file generated by xsd.exe has an incorrect property type.
        /// Edit the file to change scheduleSupportingDataObservationCodedValuesCodedValue[][] to scheduleSupportingDataObservationCodedValuesCodedValue[]
        /// TODO: find a better way to fix this. Partial classes?
        /// </remarks>
        public static scheduleSupportingData Schedule { get; } = ScheduleCollection.Create();

        public static IDictionary<IAntigenIdentifier, antigenSupportingData> Antigen { get; } = new AntigenCollection();

        public static TestcaseCollection Testcases { get; } = new TestcaseCollection();
    }
}
