using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Serialization;
using Cdsi.SupportingData;

namespace Cdsi
{
    public static class Reference
    {
        public static double Version => 4.5;

        /// <remarks>
        /// As of .NET Core 3.1 the ScheduleSupportingData.cs file generated by xsd.exe has an incorrect property type.
        /// Edit the file to change scheduleSupportingDataObservationCodedValuesCodedValue[][] to scheduleSupportingDataObservationCodedValuesCodedValue[]
        /// TODO: find a better way to fix this. Partial classes?
        /// </remarks>
        public static scheduleSupportingData Schedule
        {
            get
            {
                var name = "Cdsi.SupportingData.xml.ScheduleSupportingData.xml";
                var assembly = Assembly.GetExecutingAssembly();
                var resource = assembly.GetManifestResourceStream(name);
                var deserializer = new XmlSerializer(typeof(scheduleSupportingData));
                return (scheduleSupportingData)deserializer.Deserialize(resource);
            }
        }

        public static IDictionary<object, antigenSupportingData> Antigen { get; } = new AntigenData();
    }

    public class AntigenData : IDictionary<object, antigenSupportingData>
    {
        public antigenSupportingData this[object key]
        {
            get
            {
                var name = $"Cdsi.SupportingData.xml.AntigenSupportingData- {key}-508.xml";
                var assembly = Assembly.GetExecutingAssembly();
                var resource = assembly.GetManifestResourceStream(name);
                var deserializer = new XmlSerializer(typeof(antigenSupportingData));
                return (antigenSupportingData)deserializer.Deserialize(resource);
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public ICollection<object> Keys
        {
            get
            {
                var re = new Regex("cdsi\\.supportingData\\.xml\\.AntigenSupportingData- (.*)-508\\.xml");
                var assembly = Assembly.GetExecutingAssembly();
                var resources = assembly.GetManifestResourceNames();
                return resources.Where(r => r.EndsWith(".xml")).Select(r => (object)re.Match(r).Groups[1].Value).ToList();
            }
        }


        public ICollection<antigenSupportingData> Values => Keys.Select(k => this[k]).ToList();

        public int Count => Keys.Count;

        public bool IsReadOnly => true;

        public void Add(object key, antigenSupportingData value)
        {
            throw new NotImplementedException();
        }

        public void Add(KeyValuePair<object, antigenSupportingData> item)
        {
            throw new NotImplementedException();
        }

        public void Clear()
        {
            throw new NotImplementedException();
        }

        public bool Contains(KeyValuePair<object, antigenSupportingData> item)
        {
            return item.Key.Equals(this[item.Key]);
        }

        public bool ContainsKey(object key)
        {
            return Keys.Contains(key);
        }

        public void CopyTo(KeyValuePair<object, antigenSupportingData>[] array, int arrayIndex)
        {
            throw new NotImplementedException();
        }

        public override bool Equals(object obj)
        {
            return base.Equals(obj);
        }

        public IEnumerator<KeyValuePair<object, antigenSupportingData>> GetEnumerator()
        {
            return Keys.Select(k => new KeyValuePair<object, antigenSupportingData>(key: k, value: this[k])).GetEnumerator();
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public bool Remove(object key)
        {
            throw new NotImplementedException();
        }

        public bool Remove(KeyValuePair<object, antigenSupportingData> item)
        {
            throw new NotImplementedException();
        }

        public override string ToString()
        {
            return base.ToString();
        }

        public bool TryGetValue(object key, [MaybeNullWhen(false)] out antigenSupportingData value)
        {
            var success = true;
            try
            {
                value = this[key];
            }
            catch
            {
                value = null;
                success = false;
            }
            return success;
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
